spring:
  datasource:
    url: jdbc:sqlserver://biz.db.dev.ad.jinyinmao.com.cn:1433;DatabaseName=JYMOper2
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: db-admin-dev
    password: 0SmDXp8i7MRfg29HJk1N
  jpa:
      database: sql_server
      hibernate:
             naming:
               physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
             ddl-auto: none
      show-sql: true
      database-platform: org.hibernate.dialect.SQLServer2008Dialect