spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: root
    password: root
  jpa:
      database: sql_server
      hibernate:
             ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.SQLServer2008Dialect