spring:
  datasource:
    url: jdbc:sqlserver://biz.db.dev.ad.jinyinmao.com.cn:1433;DatabaseName=JYMOper2
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: db-admin-dev
    password: 0SmDXp8i7MRfg29HJk1N
    #----------Druid----------
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
        #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j

  jpa:
      database: sql_server
      hibernate:
             naming:
               physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
             ddl-auto: none
      show-sql: true
      database-platform: org.hibernate.dialect.SQLServer2008Dialect